[package]
name = "postgres_sample"
version = "0.1.0"
authors = ["Kevin Kondratuk <paintface07@gmail.com>"]

[dependencies]
#postgres = "0.15.1"
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv= "0.9.0"